version: 2.1

jobs:
  build:
    macos:
      xcode: 14.2.0

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            brew update
            brew install node
            brew install watchman
            npm install -g react-native-cli
            yarn install

      - run:
          name: Deintegrate CocoaPods
          command: cd ios && pod deintegrate

      - run:
          name: Gem CocoaPods
          command: cd ios && gem install cocoapods

      - run:
          name: Update CocoaPods
          command: cd ios && pod update

      - run:
          name: Install CocoaPods
          command: cd ios && pod install

      - run:
          name: IOS Dir Look 
          command: cd ios && ls
          
      - run:
          name: Archive the App
          command: |
            xcodebuild archive -workspace ios/CrowdSync.xcworkspace -scheme CrowdSync -archivePath build/CrowdSync.xcarchive

      - run:
          name: Upload to TestFlight
          command: |
            xcrun altool --upload-app -f build/CrowdSync.xcarchive -u bcollins@crowdsync.net -p "@keychain:APP_STORE_CONNECT_API_KEY" --verbose

      - run:
          name: Build iOS app
          command: |
            yarn ios:build
