version: 2.1

jobs:
  build:
    macos:
      xcode: 14.2.0

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            brew update
            brew install node
            brew install watchman
            npm install -g react-native-cli
            yarn install

      - run:
          name: Deintegrate CocoaPods
          command: cd ios && pod deintegrate

      - run:
          name: Gem CocoaPods
          command: cd ios && gem install cocoapods

      - run:
          name: Update CocoaPods
          command: cd ios && pod update

      - run:
          name: Install CocoaPods
          command: cd ios && pod install

      - run:
          name: IOS Dir Look 
          command: cd ios && ls

      - run:
          name: Build iOS app
          command: |
            yarn ios:build
