version: 2.1

jobs:
  pilot-deploy:
    macos:
      xcode: 14.2.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: ios build_and_export_ipa

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd ios && bundle install
            
      - run:
          name: Build and Export IPA
          command: bundle exec fastlane $FASTLANE_LANE

workflows:
  build-test-workflow:
    jobs:
      - pilot-deploy