version: 2.1

jobs:
  build:
    macos:
      xcode: 14.2.0

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            brew update
            brew install node
            brew install watchman
            npm install -g react-native-cli
            yarn install

      - run:
          name: See Location
          command: pwd

      - run:
          name: Deintegrate CocoaPods
          command: pod deintegrate

      - run:
          name: Update CocoaPods
          command: pod update

      - run:
          name: Build iOS app
          command: |
            yarn ios:build
