version: 2.1

executors:
  macos-executor:
    docker:
      - image: circleci/macos:latest

jobs:
  build:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            brew update
            brew install node
            brew install watchman
            npm install -g react-native-cli
            yarn install

      - run:
          name: Build iOS app
          command: |
            yarn ios:build
