platform :ios do
  before_all do
    setup_circle_ci
  end
  lane :increment_build do
    increment_build_number(
      build_number: ENV['CIRCLE_BUILD_NUM'],
	  xcodeproj: "./ios/CrowdSync.xcodeproj"
    )
  end

  lane :build_and_export_ipa do
    increment_build # Call the increment_build lane to increment the build number
	app_store_connect_api_key
	
	match(type: "appstore")
    gym(
		xcargs: "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=",
		scheme: "CrowdSync",
		export_method: "development"
	)
	
	pilot(
		skip_submission: true
	)
  end
end
