platform :ios do
  lane :increment_build do
    increment_build_number(
      build_number: ENV['CIRCLE_BUILD_NUM'] # Use the CircleCI build number
    )
  end

  lane :build_and_export_ipa do
    increment_build # Call the increment_build lane to increment the build number
    gym(
      workspace: "ios/CrowdSync.xcworkspace",
      scheme: "CrowdSync",
      export_method: "app-store", # or other export method
      export_options: {
        method: "app-store", # or other export method
        signingStyle: "automatic",
        uploadBitcode: true,
        compileBitcode: true
      }
    )
  end
end
